### ISSUE TITLE
Get UKCP18 Plugin working.

### ISSUE THREAD

**Issue by agstephens** [ukcp-data/cc-plugin-ukcp18#1]
1. Copy instructions at: https://github.com/eustace-test/cc-plugin-eustace/blob/master/README.md
2. Start by cloning:  https://github.com/eustace-test/cc-plugin-eustace
3. Then copy the content of that repo (without the `.git` dirs) to your `cc-plugin-ukcp18` repo and make changes so that any mention of "eustace" (upper/lower/mixed) case becomes the equivalent "ukcp18". This will involve renaming directories, classes, readmes, modules, `setup.py`, code and a CDL template file.
4. Try to get it running with the command:
```compliance-checker --test ukcp18-core --test ukcp18-station ./cc_plugin_ukcp18/tests/data/ukcp18/test_cdl_global_atts.nc```

**Comment by antony-wilson** [comment]
Commit #52d9b20 resolves this issue
